package com.yang.dao;

import com.yang.bean.UserEntity;

public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TEST
     *
     * @mbggenerated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DB2ADMIN.TEST
     *
     * @mbggenerated
     */
    int insertSelective(UserEntity record);
}