package com.yang.bean;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.CUSTOMER.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.CUSTOMER.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB2ADMIN.CUSTOMER.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.CUSTOMER.ID
     *
     * @return the value of DB2ADMIN.CUSTOMER.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.CUSTOMER.ID
     *
     * @param id the value for DB2ADMIN.CUSTOMER.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.CUSTOMER.PASSWORD
     *
     * @return the value of DB2ADMIN.CUSTOMER.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.CUSTOMER.PASSWORD
     *
     * @param password the value for DB2ADMIN.CUSTOMER.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB2ADMIN.CUSTOMER.USERNAME
     *
     * @return the value of DB2ADMIN.CUSTOMER.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB2ADMIN.CUSTOMER.USERNAME
     *
     * @param username the value for DB2ADMIN.CUSTOMER.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}