package com.yang.bean;

public class UserFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.c_id
     *
     * @mbggenerated
     */
    private Long cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.f_date
     *
     * @mbggenerated
     */
    private String fDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.f_name
     *
     * @mbggenerated
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.f_parent
     *
     * @mbggenerated
     */
    private String fParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.f_size
     *
     * @mbggenerated
     */
    private String fSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.f_type
     *
     * @mbggenerated
     */
    private String fType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.f_url
     *
     * @mbggenerated
     */
    private String fUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.isfolder
     *
     * @mbggenerated
     */
    private Integer isfolder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.islock
     *
     * @mbggenerated
     */
    private Integer islock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.id
     *
     * @return the value of userfile.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.id
     *
     * @param id the value for userfile.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.c_id
     *
     * @return the value of userfile.c_id
     *
     * @mbggenerated
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.c_id
     *
     * @param cId the value for userfile.c_id
     *
     * @mbggenerated
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.f_date
     *
     * @return the value of userfile.f_date
     *
     * @mbggenerated
     */
    public String getfDate() {
        return fDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.f_date
     *
     * @param fDate the value for userfile.f_date
     *
     * @mbggenerated
     */
    public void setfDate(String fDate) {
        this.fDate = fDate == null ? null : fDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.f_name
     *
     * @return the value of userfile.f_name
     *
     * @mbggenerated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.f_name
     *
     * @param fName the value for userfile.f_name
     *
     * @mbggenerated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.f_parent
     *
     * @return the value of userfile.f_parent
     *
     * @mbggenerated
     */
    public String getfParent() {
        return fParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.f_parent
     *
     * @param fParent the value for userfile.f_parent
     *
     * @mbggenerated
     */
    public void setfParent(String fParent) {
        this.fParent = fParent == null ? null : fParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.f_size
     *
     * @return the value of userfile.f_size
     *
     * @mbggenerated
     */
    public String getfSize() {
        return fSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.f_size
     *
     * @param fSize the value for userfile.f_size
     *
     * @mbggenerated
     */
    public void setfSize(String fSize) {
        this.fSize = fSize == null ? null : fSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.f_type
     *
     * @return the value of userfile.f_type
     *
     * @mbggenerated
     */
    public String getfType() {
        return fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.f_type
     *
     * @param fType the value for userfile.f_type
     *
     * @mbggenerated
     */
    public void setfType(String fType) {
        this.fType = fType == null ? null : fType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.f_url
     *
     * @return the value of userfile.f_url
     *
     * @mbggenerated
     */
    public String getfUrl() {
        return fUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.f_url
     *
     * @param fUrl the value for userfile.f_url
     *
     * @mbggenerated
     */
    public void setfUrl(String fUrl) {
        this.fUrl = fUrl == null ? null : fUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.isfolder
     *
     * @return the value of userfile.isfolder
     *
     * @mbggenerated
     */
    public Integer getIsfolder() {
        return isfolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.isfolder
     *
     * @param isfolder the value for userfile.isfolder
     *
     * @mbggenerated
     */
    public void setIsfolder(Integer isfolder) {
        this.isfolder = isfolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.islock
     *
     * @return the value of userfile.islock
     *
     * @mbggenerated
     */
    public Integer getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.islock
     *
     * @param islock the value for userfile.islock
     *
     * @mbggenerated
     */
    public void setIslock(Integer islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.md5
     *
     * @return the value of userfile.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.md5
     *
     * @param md5 the value for userfile.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }
}